ingress:
  customAnnotations:
    cert-manager.io/cluster-issuer: ${cluster_issuer}
    external-dns.alpha.kubernetes.io/hostname: ${hostname}
    external-dns.alpha.kubernetes.io/target: ${ip}
    kubernetes.io/tls-acme: "true"
  name: nginx-ingress-controller
  ingressClassName: nginx
  tls:
  - hosts:
    - ${hostname}
    secretName: ${hostname}-certificate
