ingress:
  annotations:
    cert-manager.io/cluster-issuer: ${cluster_issuer}
    external-dns.alpha.kubernetes.io/hostname: ${hostname}}
    external-dns.alpha.kubernetes.io/target: ${ip}
    kubernetes.io/tls-acme: "true"
  enabled: true
  host: ${hostname}
  tls:
  - hosts:
    - ${hostname}
    secretName: ${hostname}-certificate
