global:
  tlsDisable: false

server:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: ${cluster_issuer}
      external-dns.alpha.kubernetes.io/hostname: ${hostname}
      external-dns.alpha.kubernetes.io/target: ${ip}
      kubernetes.io/tls-acme: "true"
    enabled: true
    hosts:
    - host: ${hostname}
      paths:
      - /
    ingressClassName: nginx
    tls:
    - hosts:
      - ${hostname}
      secretName: ${hostname}-certificate

  image:
    repository: "hashicorp/vault"
    tag: "1.17.2"

  dataStorage:
    enabled: true
  auditStorage:
    enabled: true

  service:
    targetPort: 8202

  volumes:
    - name: userconfig-vault-server-tls
      secret:
        defaultMode: 420
        secretName: ${vault_certificate_secret}

  volumeMounts:
    - mountPath: /vault/userconfig/vault-server-tls
      name: userconfig-vault-server-tls
      readOnly: true

  extraEnvironmentVars:
    VAULT_ADDR: 'http://127.0.0.1:8202'

  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true

        
        listener "tcp" {
          address = "[::]:8202"
          tls_disable = "true"
        }

        listener "tcp" {
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_disable = "false"
          tls_cert_file = "/vault/userconfig/vault-server-tls/tls.crt"
          tls_key_file  = "/vault/userconfig/vault-server-tls/tls.key"
          tls_client_ca_file = "/vault/userconfig/vault-server-tls/ca.crt"
          tls_disable_client_certs = "true"
          tls_require_and_verify_client_cert="false"
        }

        service_registration "kubernetes" {}

        storage "raft" {
          path = "/vault/data"

          retry_join {
            leader_api_addr = "https://vault-0.vault-internal:8200"
            leader_client_cert_file  = "/vault/userconfig/vault-server-tls/tls.crt"
            leader_client_key_file   = "/vault/userconfig/vault-server-tls/tls.key"
            leader_ca_cert_file    = "/vault/userconfig/vault-server-tls/ca.crt"
          }
          retry_join {
            leader_api_addr = "https://vault-1.vault-internal:8200"
            leader_client_cert_file  = "/vault/userconfig/vault-server-tls/tls.crt"
            leader_client_key_file   = "/vault/userconfig/vault-server-tls/tls.key"
            leader_ca_cert_file    = "/vault/userconfig/vault-server-tls/ca.crt"
          }
          retry_join {
            leader_api_addr = "https://vault-2.vault-internal:8200"
            leader_client_cert_file  = "/vault/userconfig/vault-server-tls/tls.crt"
            leader_client_key_file   = "/vault/userconfig/vault-server-tls/tls.key"
            leader_ca_cert_file   = "/vault/userconfig/vault-server-tls/ca.crt"
          }
        }


