server:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: ${cluster_issuer}
      external-dns.alpha.kubernetes.io/hostname: ${hostname}
      external-dns.alpha.kubernetes.io/target: ${ip}
      kubernetes.io/tls-acme: "true"
    enabled: true
    hosts:
    - host: ${hostname}
      paths:
      - /
    ingressClassName: nginx
    tls:
    - hosts:
      - ${hostname}
      secretName: ${hostname}-certificate

  image:
    repository: "hashicorp/vault"
    tag: "1.17.2"

  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true

        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }

        storage "raft" {
          path = "/vault/data"
        }

        service_registration "kubernetes" {}

        retry_join {
          leader_api_addr = "http://vault-0.$${SERVICE}:8200"
        }
        retry_join {
          leader_api_addr = "http://vault-1.$${SERVICE}:8200"
        }
        retry_join {
          leader_api_addr = "http://vault-2.$${SERVICE}:8200"
        }

